version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro # ro = read only, to prevent container from making changes to files
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=innovation
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=e2de85d28607c1dd011dcc1648d2691f0ff579021b45cd3cb51694b2b161ad0f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=920
      - pass=mypassE

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: